
class FrameBuffer:
    RGB_IMAGE = "rgbImage"
    BGR_IMAGE = "bgrImage"
    GRAY_IMAGE = "grayImage"
    PREDICTION = "prediction"
    GROUND_TRUTH = "gt"
    RT_MATRIX = "RtMtx"
    RT_MATRIX_INVERSE = "RtMtxInverse"
    POINTS_2D = "points2d"
    POINTS_2D_NEXT_FRAME = "points2dNextFrame"
    POINTS_3D = "points3d"
    TRIANGULATION_ERROR_XY = "trErrorXY"
    TRIANGULATION_ERROR_Z = "trErrorZ"
    CALIBRATED_PREDICTION = "calibratedPrediction"
    CALIBRATED_PREDICTION_ERROR = "depthError"
    CALIBRATED_PREDICTION_THRESHOLD_ERROR = "depthErrorThreshold"
    KEYPOINTS = "kp"
    DESCRIPTORS = "des"
    SCALE_FACTOR = "scaleFactor"
    SHIFT_FACTOR = "shiftFactor"
    TIMESTAMP = "timestamp"
    ROI = "roi"
    LOCATION = "location"
    ROTATION = "rotation"